spring:
  application:
    name: javaflix

  datasource:
    url: jdbc:postgresql://localhost:5432/javaflix
    username: ${DB_USER}
    password: ${DB_SENHA}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-plataform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true


  flyway:
    enabled: true

